import Head from 'next/head';
import Image from 'next/image';
import { Example } from '@web/components/src/components/atoms/example/Example';
import { Button } from '@web/components/src/components/atoms/button/Button';
import { TextAndButton } from '@web/components/src/components/molecules/text-and-button';

// eslint-disable-next-line max-lines-per-function
export default function Home(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>
            <Example />
          </h1>
          <Button label="Example button" />
          <Button label="Example primary button" primary />
        </div>
        <div>
          <h2>Molecules Example</h2>
          <TextAndButton label="Molecules" />
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
      </footer>
    </div>
  );
}
