name: Web-components jobs
on:
  push:
    paths:
      - ".github/workflows/web-components.yml"
      - "packages/web-components/**"
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.6.2'
      - name: Cache node_modules and .yarn
        id: cache_node_modules_and_yarn
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.node_modules
            ~/.yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Yarn install
        if: steps.cache_node_modules_and_yarn.outputs.cache-hit != 'true'
        run: yarn --immutable
  lint:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: yarn workspace web-components eslint
  # formatter:
  #   needs: setup
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: yarn workspace web-components prettier
  # tsc:
  #   needs: setup
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: yarn workspace web-components tsc
  # jest:
  #   needs: setup
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: yarn workspace web-components test
  # test:
  #   needs: ['lint', 'formatter', 'tsc', 'jest']
  #   runs-on: ubuntu-20.04
